name: ficcanaso
description: The Dart analyzer settings and best practices used. forked from pedantic
version: 3.0.9
repository: https://github.com/dbbd59/ficcanaso

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^4.7.0
